### ISSUE TITLE
redis_slave can't reach redis_master when using docker-compose

### ISSUE THREAD

**Issue by davock** [madeindra/setup-guide#2]
Although you are using port `6379` for both external and docker network here: 

```
redis_master:
    image: redis:5
    container_name: redis_master
    ports:
      - '6379:6379'
    volumes:
      - /tmp/redis_master:/data
```

When I run docker compose `redis-slave` can't reach `redis-master` and produces this error: 

```Error condition on socket for SYNC: Connection refused```

Not sure why this happens with your approach of using the `${EXTERNAL_HOST}` but a more neat way to do it in docker is to use the docker network hostnames, so instead of 

```redis-server --port 6380 --slaveof "${EXTERNAL_HOST}" 6379 --slave-announce-ip "${EXTERNAL_HOST}"```  

you can do 

```redis-server --port 6380 --slaveof "redis_master" 6379 --slave-announce-ip "${EXTERNAL_HOST}"```   

Because within docker network redis matster is `http://redis-master`. This solves the issue for me.

Anyways, I'm still curious about why your approach doesn't work for me. If you have some objection to my approach let me know. I'm just doing my first steps in the server and may be missing something.
